name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# This profile is copied to a non-core location by
# \Drupal\Tests\config\Functional\ConfigInstallProfileUnmetDependenciesTest.
core_version_requirement: '*'
hidden: true
install:
  - action
  - language
  - testing_config_overrides_module
  - tour

# Information added by Drupal.org packaging script on 2021-12-09
version: '9.3.0'
project: 'drupal'
datestamp: 1639051328
